### ISSUE TITLE
Problems uploading documents 

### ISSUE THREAD

**Issue by c0r3dump3d** [owncloud/documents#640]
Hi, I have installed in owncloud 9.0.1.3 the document plugin version 0.13.0, when I try to upload a odt file from the app upload menu nothing happen, I can not see the uploaded document and no error log it's reported .... only in the firebug console I see this error message:

```
TypeError: window.FileList.findFileEl is not a function
	

var $tr = window.FileList.findFileEl(file.name);

```
	

Thank you in advance

**Comment by lebardix** [comment]
same problem

Steps to reproduce

    Goto in Documents
    Choose Upload ("Téléverser" in french)
    a file windows chooser appear
    select a .odt file
    select Open ("Ouvrir")

Expected behaviour

with release OC 8.0.4 stable action upload the selected file
with release OC 9.0.2 stable action do nothing, no upload file
Actual behaviour

with release OC 9.0.2 stable do nothing, no upload
Server configuration

ownCloud version:
OC 9.0.2 stable
Client configuration

Browser:
Iceweasel 38.8.0
Operating system:
Linux Debian wheezy

Insert your browser log here, this could for example include:
(i have change only domain)

goto https://laperouse.mydomain.tld/index.php/apps/documents/index

a) The javascript console log  
```
GET 
XHR 
https://laperouse.mydomain.tld/ocs/v2.php/apps/notifications/api/v1/notifications [HTTP/1.1 200 OK 325ms]
GET 
XHR 
https://laperouse.mydomain.tld/ocs/v2.php/apps/notifications/api/v1/notifications [HTTP/1.1 200 OK 310ms]
GET 
XHR 
https://laperouse.mydomain.tld/ocs/v2.php/apps/notifications/api/v1/notifications [HTTP/1.1 200 OK 288ms]
L'utilisation de « getAttributeNode() » est obsolète. Utiliser « getAttribute() » à la place. jquery.min.js:156:0
TypeError: window.FileList.findFileEl is not a function file-upload.js:264:12
GET 
XHR 
https://laperouse.mydomain.tld/ocs/v2.php/apps/notifications/api/v1/notifications [HTTP/1.1 200 OK 2704ms]
GET 
XHR 
https://laperouse.mydomain.tld/ocs/v2.php/apps/notifications/api/v1/notifications
```

b) the JS function 

```
    /**
     * Returns whether the given file is known to be a received shared file
     *
     * @param {Object} file file
     * @return {bool} true if the file is a shared file
     */
    _isReceivedSharedFile: function(file) {
        if (!window.FileList) {
            return false;
        }
        var $tr = window.FileList.findFileEl(file.name);   <--line here
        if (!$tr.length) {
            return false;
        }

        return ($tr.attr('data-mounttype') === 'shared-root' && $tr.attr('data-mime') !== 'httpd/unix-directory');
    },
```
-------------------------------------------------------------------------------
with same browser connect to OC8.0.4 (one another server), the console JS is with uploaded file  OK

```
GET 
https://webcloud.zaclys.com/apps/documents/js/3rdparty/resources/dojo/resources/blank.gif [HTTP/1.1 200 OK 22ms]
L'utilisation de « getAttributeNode() » est obsolète. Utiliser « getAttribute() » à la place. jquery.min.js:156:0
POST 
XHR 
https://webcloud.zaclys.com/index.php/apps/files/ajax/upload.php [HTTP/1.1 200 OK 2058ms]
GET 
XHR 
https://webcloud.zaclys.com/index.php/apps/documents/ajax/documents/list [HTTP/1.1 200 OK 185ms]
TypeError: FileList.highlightFiles is not a function file-upload.js:447:7
GET 
https://webcloud.zaclys.com/index.php/core/preview.png
```

**Comment by filkeith** [comment]
I've tried to fix that. And now I can upload files. (Haven't tested all scenarios, but simple uploading works).
1) Open file <your installation dir>/owncloud/apps/documents/js/documents.js
2) Go to 671 line. You'll see there
`FileList = FileList || {};

FileList.getCurrentDirectory = function(){
	return $('#dir').val() || '/';
};`
3) Add this
```
FileList = FileList || {};

FileList.getCurrentDirectory = function(){
	return $('#dir').val() || '/';
};
FileList.findFileEl = function(fileName){
	return jQuery('li:contains("' + fileName + '")');
};
FileList.findFile = function(fileName){
	return OC.Files.FileInfo(fileName);
};
```
4) PROFIT

**Comment by lebardix** [comment]
works fine in OC9.0
thanks ;)

**Comment by lebardix** [comment]
On Thu, 12 May 2016 23:41:42 -0700
filkeith <notifications@github.com> wrote:

> I've tried to fix that. And now I can upload files. (Haven't tested
> all scenarios, but simple uploading works). 1) Open file <your
> installation dir>/owncloud/apps/documents/js/documents.js 2) Go to
> 671 line. You'll see there `FileList = FileList || {};
> 
> FileList.getCurrentDirectory = function(){
> 	return $('#dir').val() || '/';
> };`
> 3) Add this
> ```
> FileList = FileList || {};
> 
> FileList.getCurrentDirectory = function(){
> 	return $('#dir').val() || '/';
> };
> FileList.findFileEl = function(fileName){
> 	return jQuery('li:contains("' + fileName + '")');
> };
> FileList.findFile = function(fileName){
> 	return OC.Files.FileInfo(fileName);
> };
> ```
> 4) PROFIT
> 
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/owncloud/documents/issues/640#issuecomment-218963979

Hi,

Works fine

thanks

Marc Ferraton

**Comment by c0r3dump3d** [comment]
Hi, perfect!! It's working fine in 9.0.2 (stable).

**Comment by RealRancor** [comment]
@c0r3dump3d Please re-open if you need to manually modify stuff within the app source code to get a functionality to work

**Comment by VicDeo** [comment]
@RealRancor  nope, it's fixed ;) https://github.com/owncloud/documents/pull/652

**Comment by RealRancor** [comment]
Ahh, thanks. Thought this wasn't fixed because of the user reported upload issues in https://github.com/owncloud/documents/issues/666 and no reference to a fix in here.
